# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Qi Yu
description: >- # this means to ignore newlines until "baseurl:"
  Qi Yu's homepage
baseurl: "" # the subpath of the site
#url: "https://qi-yu.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: About
      slug: /
    - name: Research Projects
      slug: /projects
    - name: Publications & Talks
      slug: /publication
#    - name: Teaching
#      slug: /teaching
    - name: Paintings
      slug: /horcrux
    - name: Maybe Funny
      slug: /miscellaneous
    - name: Qi's Chat
      slug: /blog

footer:
  show_powered_by: true
#  contact:
#    - name: Email
#      value: qi [dot] yu [at] uni-konstanz [dot] de
#      link: mailto:qi.yu@uni-konstanz.de
#  follow:
#    - name: GitHub
#      link: http://github.com/qi-yu

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
